version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "${HTTP_HOST_PORT}:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    restart: always
  db:
    image: percona:ps-8.0.36-28
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    expose:
      - "3306"



